### ISSUE TITLE
Seems to be a tga in riff but not sure

### ISSUE THREAD

**Issue by RolandTi** [PKBeam/RiffExt#1]
Hello,
thanks for your application,
I make it on macos and  it's working. But I'm not sure if the header of my riff file is correct because the .wem file is supposed to be a multiples tga (old targa pictures). I tried to rename it. But it's not working.

Hace you any clue ? :-) thanks !
<img width="1289" alt="Capture d’écran 2020-11-09 à 22 40 06" src="https://user-images.githubusercontent.com/28786873/98599686-af0dd180-22dc-11eb-9e8d-9dea9e43f9eb.png">
<img width="1289" alt="Capture d’écran 2020-11-09 à 22 40 51" src="https://user-images.githubusercontent.com/28786873/98599697-b339ef00-22dc-11eb-969d-18980522a344.png">

**Comment by PKBeam** [comment]
I think this may be an instance of the extractor falsely identifying a RIFF file. It only checks for the letters "RIFF" in the file.
If it doesn't follow this format (http://soundfile.sapp.org/doc/WaveFormat/) then it's probably a false positive by the extractor.

**Comment by RolandTi** [comment]
Ok, thanks !
