### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by sirensynapse** [PKBeam/RiffExt#2]
How does this work? I only know how to click on an exe file and point to the right folder, but I can follow instructions well. :)

**Comment by PKBeam** [comment]
You need to add the riffext/riffscan executable to the folder with the file you want to operate on, open a command prompt in that folder, then follow the instructions under **Usage**.

**Comment by sirensynapse** [comment]
Thanks. :)
There are hundreds of songs, surely I don't have to repeat that for each
file? Do you recall where they even are in the game folder?

**Comment by sirensynapse** [comment]
Sorry, referring to baldur's gate III. :)

**Comment by sirensynapse** [comment]
Edit...got it. Now how to deal with .wem files.... ??

**Comment by PKBeam** [comment]
In regards to your first question, all the music for BG3 are stored in one file (SharedSounds.pak). 
RiffExt and RiffScan will operate on every music track in the file.

To convert .wem files into a more common format you should use vgmstream (a link is at the bottom of the README doc).
Foobar2000 may be able to play .wem files directly.

**Comment by sirensynapse** [comment]
As usual, everything on github is utterly geared towards programmers with
almost no instructions for laymen. Sigh.
vgmstream is just a zip file full of bizarre files that mean nothing to me.
How the hell do I use said mess to do extract files?

**Comment by sirensynapse** [comment]
No instructions how to install the supposed foobar extension.....

**Comment by sirensynapse** [comment]
Never mind, foobar had a link to it, from their end. Thanks, hopefully that
will be the end of this. :)

**Comment by sirensynapse** [comment]
Which file has the music, please? :) It's not SharedSounds.pak.

**Comment by PKBeam** [comment]
You can do `riffscan.exe <filename>` in a command line to preview what files contain audio data.

If you do this with SharedSounds.pak it will show you about 36,000 audio files contained inside, which you can extract all at once using `riffext.exe SharedSounds.pak` with a command line opened inside `Baldurs Gate 3/Data`.

Only a few of these sound files will correspond to actual music - most of them are sound effects. The music files seem to be numbered between 14314-14495 inclusive. (Music files are usually 44.1 kHz and will be longer than about 10 seconds or so - you can check for this by using RiffScan to output to a csv spreadsheet - `riffscan.exe SharedSounds.pak >> out.csv`. Microsoft Excel handles csv files in a nonstandard way that requires `SEP=,` to be added to the first line of the file).

For reference, a shift + right-click inside a directory in Windows Explorer brings up a menu with the option to open Powershell in that folder. You need to unselect any files before doing the shift + right-click.

For vgmstream, you need to download the `test.zip` folder from their releases page on GitHub (no idea why it's called that) and use `test.exe` to convert `.wem` files  e.g. `text.exe -o output.wav input.wem`. Or you can just play them directly with Foobar2000.

**Comment by sirensynapse** [comment]
Ok, thanks a lot. I extracted only the largest wem files and they were
all ambient, so assumed the rest, which are all very very small
couldn't possibly be music files. ?? But I'll go look.

**Comment by sirensynapse** [comment]
Jesus, I extracted the wems earlier, and there were only just under 10k,
not 36k of them. But now, I deleted them and can't use riffscan or riffext
at all. I copy/pasted your exact text and this is all I get. Feel like
gonna pull my hair out here. :P
Microsoft Windows [Version 10.0.18363.1316]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\Baldurs Gate 3\Data>riffscan.exe <SharedSounds.pak>
The syntax of the command is incorrect.

D:\Baldurs Gate 3\Data>riffext.exe <SharedSounds.pak>
The syntax of the command is incorrect.

D:\Baldurs Gate 3\Data>
D:\Baldurs Gate 3\Data>

**Comment by sirensynapse** [comment]
Nope, restored from trash, my SharedSounds files are 100% ambient, I tested
all larger than 4k in size. Must have a different game build/folder setup
than yours. Only 10k wems, like I said. I don't see where the damned music
might be, guess I have to look at each pak file 1 by 1.

**Comment by sirensynapse** [comment]
Still can't get riffs to work again, madness. No reason. Typed perfectly.

**Comment by PKBeam** [comment]
The <> brackets are not supposed to be typed literally (sorry about that confusion), you should replace the entire thing with just the filename - e.g. 
`riffscan.exe SharedSounds.pak`
`riffext.exe SharedSounds.pak`

Try `riffext.exe SharedSounds.pak -i 14327`. That should give a music file.
I tested it myself on the latest version of the game. My SharedSounds.pak is 3,207,083 KB as reported by Windows.

**Comment by sirensynapse** [comment]
Ja, just realized that, doh. :)

**Comment by sirensynapse** [comment]
Still don't see the music there; will try other paks now.

**Comment by sirensynapse** [comment]
Maybe it hadn't extracted them all, stopped part way for some reason....

**Comment by sirensynapse** [comment]
Yes that was it; flying past 10k now. Sorry, I"m such a noob, must have
accidentally closed the window or something. haha
sigh

**Comment by sirensynapse** [comment]
Nor riffext keeps crashing at just before #13000, even when I reduced the
load by setting the min size at 500000. Any ideas?
